title: "My Algo Blog"
description: "算法笔记与模板整理"
url: "https://haibara121ai.github.io"
baseurl: "/my_blog"

theme: minima

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

header_pages:
  - categories.md
  - tags.md
  - about.md
